### ISSUE TITLE
update to node 8

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#167]
- [x] add cli-engine-docker node 8 image
- [ ] test heroku-cli on node 8
- [ ] set engine to node >=8 in cli-engine/cli-engine-command/etc
- [ ] wait for https://github.com/node-nock/nock/issues/928
- [ ] see if we can drop string dependency for string.padStart()
- [ ] see if we can remove EPIPE handler

**Comment by stevenvachon** [comment]
~~Why wait for #928 ?~~

**Comment by jdx** [comment]
because it breaks our build

**Comment by stevenvachon** [comment]
~~The build breaks without that code, though.~~

Wrong repo.

**Comment by stevenvachon** [comment]
Oops.. wrong repo.

**Comment by RasPhilCo** [comment]
Done https://github.com/heroku/cli-engine/blob/master/package.json#L69
