### ISSUE TITLE
Engine should be consumable by others

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#169]
Currently cli-engine is just used to build the heroku-cli with the goal of one day having an open source platform for others to build similar CLIs. Some work needs to be done for this to happen, however:

- [x] single-repo CLI (don't require a core plugin)
- [x] document releasing custom CLIs
- [ ] write blog post on cli-engine
- [x] write "joe dev" CLI example

**Comment by schickling** [comment]
Really looking forward to seeing this :)

**Comment by hemju** [comment]
Looking forward to it as well. Any predictions on the time frame?

**Comment by jdx** [comment]
actively working on it, hopefully will be out in the next few months

**Comment by danrasmuson** [comment]
Any updates on the release of this?

**Comment by jdx** [comment]
Yes! We still need to write up docs, but we renamed the project and you can build your own CLI by running `npx oclif multI mynewcli`

**Comment by zcei** [comment]
So the whole `@cli-engine/*` packages are already obsolete again? (Was trying out your work with the old `cli-engine-'*` Flow version as well as your new namespaced TypeScript version)

**Comment by jalcine** [comment]
Can't wait for these docs!

**Comment by jdx** [comment]
@zcei technically yes, but aside from the name changes the changes to the functionality are minimal from cli-engine/* to oclif/*

**Comment by jdx** [comment]
here is an example multi-command CLI in typescript: https://github.com/oclif/example-multi-ts

**Comment by zcei** [comment]
Awesome, will give it a shot tomorrow 👍

**Comment by jdx** [comment]
docs are up, still more work to do but I think we can close this out

https://github.com/oclif/oclif

**Comment by nsamsami** [comment]
@schickling @hemju @danielrasmuson @jalcine In case you missed it, the docs are up in the new repo for this project, which is now named Open CLI Framework (oclif): https://github.com/oclif/oclif/ 

I've also created a simple "getting started" guide here: https://salesforce.quip.com/kEgcAnqZMvck

Hope you get a chance to check it out! As we're just getting started with sharing this project more widely, would really appreciate any feedback you have or just to better understand your interest and the use cases. Feel free to create an issue directly in the oclif repo or to email us directly to say hi, at heroku-cli@salesforce.com
