### ISSUE TITLE
2fa prompt not working

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#21]
2fa prompt for paranoid apps seems to just exit with code 0 for some reason:

```
heroku config:add UPDATE_HASH=foo -a paranoidapp
Setting UPDATE_HASH and restarting ⬢ toolbelt... !
Two-factor code:
```

**Comment by ransombriggs** [comment]
Fixed by https://github.com/heroku/cli/commit/e0ad11d69eee2abca277ef4be2c90ee1048d0445

**Comment by ransombriggs** [comment]
The underlying problem is that the `catch(() => then(run))` pattern in heroku-cli-util stopped working.

**Comment by ransombriggs** [comment]
Will create issues for the other two places we have this pattern so that we fix those as well.
