### ISSUE TITLE
Prompt to uninstall when plugins:link reports package already installed

### ISSUE THREAD

**Issue by edmorley** [heroku/cli-engine#239]
Hi!

If a package is already installed via `plugins:install`, trying to link a development repo of it currently results in:
```
heroku-slugs $ heroku plugins:link
Linking C:\Users\Ed\src\_todo\heroku-slugs... !
 !    heroku-slugs is already installed.
 !    Uninstall with heroku plugins:uninstall heroku-slugs
heroku-slugs $ heroku plugins:uninstall heroku-slugs
Uninstalling plugin heroku-slugs... done
heroku-slugs $ heroku plugins:link
Installing dependencies for C:\Users\Ed\src\_todo\heroku-slugs... done
```

Whilst it's only an extra two commands, perhaps:
a) the first command could instead result in:
```
 !    heroku-slugs is already installed.
 !    Uninstall? (y/N)
```
b) if the user passed say `-f` / `--force` to `plugins:link` it wouldn't even prompt but just uninstall automatically

This was using:
heroku-cli/6.12.9-d4bf599 (windows-x64) node-v8.1.4

**Comment by jdx** [comment]
it's a good idea but might be a lot harder than it sounds. When the CLI initializes it loads all the plugin data for the remainder of the session. This would require us to "unload" it. I'll look into it though since it would certainly make development easier.

**Comment by RasPhilCo** [comment]
Linked plugins are now forced every time. This will go out in heroku-cli v6.13.7 here in a day or so.

**Comment by edmorley** [comment]
Many thanks :-)
