### ISSUE TITLE
Allow namespaces to provide a description for display in root help

### ISSUE THREAD

**Issue by rbergman** [heroku/cli-engine#267]
In v5 a namespace could define a description that would be displayed in the CLI's root help.  In v6, this appears to be hardcoded to `topics for <namespace>`.  It'd be beneficial to allow a v6 namespace to provide a description somehow alongside the namespace name, possible in the cli-engine config of the plugin's `package.json`.

**Comment by jdx** [comment]
@RasPhilCo maybe for now what we could do is hardcode `force` in the CLI since a longer-term solution would probably involve the 'topics as an array' project

**Comment by rbergman** [comment]
Whatever you guys think there is fine by me... how would it look hardcoded in the CLI?

**Comment by RasPhilCo** [comment]
Solved via nested topics. And I thought we added the hardcode in for bit too, though I don't see it in the code now. Anyhow, propose closing.
