### ISSUE TITLE
unauthorized trap not working bug

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#29]
```
rbriggs@ebriggs-ltm [09:39:37] [~/src/github.com/heroku/cli] [v6]
-> % heroku apps     
 ▸    Invalid credentials provided.
Enter your Heroku credentials:
Email: %
```

**Comment by ransombriggs** [comment]
https://github.com/heroku/cli-engine/issues/21#issuecomment-289042569

**Comment by jdx** [comment]
What is this issue?

**Comment by jdx** [comment]
I mean, I understand the problem, but do you have an idea what's going wrong under the hood?

**Comment by ransombriggs** [comment]
@dickeyxxx no, I am confused by this and have not had a chance to investigate, but I wanted to talk about approaching this a different way than restarting the entire command
