### ISSUE TITLE
Multiple writers could cause corruption in the plugins cache file

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#32]
https://github.com/heroku/cli-engine/blob/7c3f8156ec9be1e248ae52d29aa3d7fb9537ba15/src/plugins.js#L112

**Comment by ransombriggs** [comment]
Multiple writers as in separate processes this might be better done as a write to temp file than rename so that it is done in a single operation

**Comment by jdx** [comment]
is `writeFileSync` not safe to use with multiple writers or something? not sure I understand the issue
