### ISSUE TITLE
`heroku pipelines` is not found

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#36]
```
$ heroku pipelines
 ▸    pipelines is not a heroku command.
 ▸    Perhaps you meant pg:links
 ▸    Run heroku help for a list of available commands.
 !    `pipelines` is not a heroku command.
 !    See `heroku help` for a list of available commands.
$ heroku help
Usage: heroku COMMAND [--app APP] [command-specific-options]
Help topics, type heroku help TOPIC for more details:
[...]
 pipelines       # manage collections of apps in pipelines
[...]
```

**Comment by KarateCowboy** [comment]
Hello

So, the reason for this is that `pipelines` is not a command in and of itself. It is a topic, under which are many plans. There is no command with the id `pipelines`. Other topic-commands will work, EG `heroku pipelines:list` will function correctly, as will `heroku pipelines:add`.

Next step: Decide whether to:

1. Dismiss as a non-issue
2. Have the command `heroku pipelines` output some informative help, noting that `pipelines` is a topic, under which there are commands
3. Alter the `heroku help` to make note that `pipelines` is a topic, not a command
4. Alias some other command to be the default action when `heroku pipelines` is run

**Comment by ransombriggs** [comment]
@KarateCowboy I think it may be the [`default: true`](https://github.com/heroku/heroku-pipelines/blob/master/commands/pipelines/list.js#L11) option that is no longer being respected

**Comment by jdx** [comment]
notably that's an option I want to remove, but we probably need it for backwards compatibility at the moment

**Comment by jdx** [comment]
Added #47 with fix
