### ISSUE TITLE
Need to port 2fa:enable to JavaScript

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#38]

**Comment by ransombriggs** [comment]
I would do this after the other 2fa commands as I have low confidence that the go version works

**Comment by ransombriggs** [comment]
@dickeyxxx I tried enable and it did not appear to work at all, do you know what is up?  I am assuming it is just dumping the API message and that there is something extra we will have to do to make this work.
```
-> % heroku auth:2fa
Two-factor authentication is not enabled
-> % heroku auth:2fa:enable
Password (typing will be hidden):
 ▸    A second authentication factor or pre-authorization is required for this request. Your account has either two-factor or a YubiKey registered.
```

**Comment by jdx** [comment]
no idea what's going on with it, I can investigate if you like

**Comment by jdx** [comment]
decided not to port since it does not function in v5
