### ISSUE TITLE
heroku git:remote broken

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#40]
Have not investigated, but likely due to `context` not being backwards compatible
```
-> % ./bin/run git:remote -a rbriggs-sushi
set git remote heroku to https://undefined/rbriggs-sushi.gi
```

**Comment by ransombriggs** [comment]
Will likely be fixed by https://github.com/heroku/cli-engine/issues/28

**Comment by ransombriggs** [comment]
@RasPhilCo all the variables [here](https://github.com/heroku/cli/blob/master/context.go#L9) should also be set to equivalent values [here](https://github.com/heroku/cli-engine/blob/master/src/legacy.js#L65).  Most of these values can be found [here](https://github.com/heroku/cli-engine-command/blob/master/src/heroku.js#L11) or [here](https://github.com/heroku/cli-engine-command/blob/master/src/config.js#L42) or [here](https://github.com/heroku/cli-engine-command/blob/master/src/config.js#L80)

**Comment by ransombriggs** [comment]
@RasPhilCo I think this line is from [here](https://github.com/heroku/heroku-git/blob/master/commands/git/remote.js#L12) where we pass in the context, which is making random things break in [here](https://github.com/heroku/heroku-git/blob/master/lib/git.js) because values are `undefined`

**Comment by KarateCowboy** [comment]
So, as I understand it, we're going address these as they pop up?

**Comment by jdx** [comment]
we can close this now right?

**Comment by ransombriggs** [comment]
Fixed in https://github.com/heroku/cli-engine/pull/55
