### ISSUE TITLE
Passing flags as args no longer causes an error

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#41]
```
-> % heroku apps:info --foobar
 ▸    Error: Unexpected flag --foobar
```
but now `--foobar` is interpreted as an argument
```
-> % ./bin/run apps:info --foobar 
 ▸    Couldn't find that app.
```

**Comment by ransombriggs** [comment]
@dickeyxxx was this intentional for a v6 feature?

**Comment by jdx** [comment]
It is intentional, an arg could potentially look like a flag. I thought v5 also acted this way, but I definitely think this is the way it should work.

**Comment by RasPhilCo** [comment]
Closing as not an issue
