### ISSUE TITLE
heroku-local exits early

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#77]
because of the cli.exit and https://github.com/heroku/heroku-local/blob/master/commands/start.js#L24 not returning a promise

**Comment by jdx** [comment]
started the work here: https://github.com/heroku/heroku-local/pull/30

**Comment by jdx** [comment]
my solution does not work at all, but it should hopefully get you on track for this one

**Comment by ransombriggs** [comment]
https://github.com/heroku/heroku-local/pull/30

**Comment by RasPhilCo** [comment]
Closed via https://github.com/heroku/heroku-local/pull/30
